baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Calendar"
    url = "/calendar/"
    weight = 2

  [[menu.main]]
    name = "Missions"
    url = "/missions/"
    weight = 3

  [[menu.main]]
    name = "Connect"
    url = "/connect/"
    weight = 4

  [[menu.main]]
    name = "Give"
    url = "/give/"
    weight = 5