baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Dade City Christian Church'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 2
    parent = "About"

  [[menu.main]]
    name = "Values and Beliefs"
    url = "/about/values-and-beliefs"
    weight = 2
    parent = "About"

  [[menu.main]]
    name = "Calendar"
    url = "/calendar/"
    weight = 2

  [[menu.main]]
    name = "Missions"
    url = "/missions/"
    weight = 3

  [[menu.main]]
    name = "Connect"
    url = "/connect/"
    weight = 4

  [[menu.main]]
    name = "Give"
    url = "/give/"
    weight = 5